sonar.projectKey=hagymareaktor_purepin
sonar.organization=hagymareaktor

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=purepin
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=plugin
#sonar.tests=tests

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclude files from analysis
# sonar.exclusions=plugin/assets/**
